### ISSUE TITLE
Doesnt work with current gevent

### ISSUE THREAD

**Issue by potchin** [rasky/geventconnpool#10]
With the latest packages in redhat 7 the module tries to import BoundedSemaphore from gevent.coros which no longer exists...

# pip install geventconnpool
Collecting geventconnpool
  Downloading geventconnpool-0.2.1.tar.gz
Collecting gevent>=0.13 (from geventconnpool)
  Downloading gevent-1.2.1-cp27-cp27mu-manylinux1_x86_64.whl (1.8MB)
    100% |████████████████████████████████| 1.8MB 918kB/s 
Collecting greenlet>=0.4.10 (from gevent>=0.13->geventconnpool)
  Downloading greenlet-0.4.11-cp27-cp27mu-manylinux1_x86_64.whl (41kB)
    100% |████████████████████████████████| 51kB 12.5MB/s 
Installing collected packages: greenlet, gevent, geventconnpool
  Running setup.py install for geventconnpool ... done
Successfully installed gevent-1.2.1 geventconnpool-0.2.1 greenlet-0.4.11
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

# python
Python 2.7.5 (default, Aug  2 2016, 04:20:16) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from geventconnpool import ConnectionPool
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/geventconnpool/__init__.py", line 5, in <module>
    from pool import ConnectionPool, retry
  File "/usr/lib/python2.7/site-packages/geventconnpool/pool.py", line 4, in <module>
    from gevent.coros import BoundedSemaphore
ImportError: No module named coros

**Comment by potchin** [comment]
The module has been renamed from gevent.coros to gevent.lock

**Comment by rasky** [comment]
done. sorry the repo is effectively unamaintained, I'll archive it
